// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwSsP5_WynoVKmc-_U7t2yn1-qt7VjI0I',
    appId: '1:771381090783:web:5a63fa91efbc367b184c6a',
    messagingSenderId: '771381090783',
    projectId: 'ordering-siam-canteen',
    authDomain: 'ordering-siam-canteen.firebaseapp.com',
    databaseURL: 'https://ordering-siam-canteen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ordering-siam-canteen.appspot.com',
    measurementId: 'G-QMWF3V531S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBcRnmh48_xXeWYNQMqq7jk4ZENJMcyyM',
    appId: '1:771381090783:android:46b370cbae5c0812184c6a',
    messagingSenderId: '771381090783',
    projectId: 'ordering-siam-canteen',
    databaseURL: 'https://ordering-siam-canteen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ordering-siam-canteen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNd9uqDt4ZNEoHmeabw3_x4I9ludy-oKA',
    appId: '1:771381090783:ios:6696c332327f2c15184c6a',
    messagingSenderId: '771381090783',
    projectId: 'ordering-siam-canteen',
    databaseURL: 'https://ordering-siam-canteen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ordering-siam-canteen.appspot.com',
    iosClientId: '771381090783-83vuhov96nipvalee6rh2op96t0n7og0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNd9uqDt4ZNEoHmeabw3_x4I9ludy-oKA',
    appId: '1:771381090783:ios:6af976df243acbc8184c6a',
    messagingSenderId: '771381090783',
    projectId: 'ordering-siam-canteen',
    databaseURL: 'https://ordering-siam-canteen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ordering-siam-canteen.appspot.com',
    iosClientId: '771381090783-v97ir293or7bqn43p0p3rckftcmsbta3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
